name: Hopping Mad
favicon: null
layout_spectrum: 0.5634855020325631
typography_spectrum: 0.21635
title: My First very intelligent Website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#49484e'
    - '#8c8b91'
    - '#000100'
    - '#047c59'
    - '#c6c3cc'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
